<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Kobuki Base Properties -->
  <xacro:property name="base_radius" value="0.175"/>
  <xacro:property name="base_height" value="0.095"/>
  <xacro:property name="wheel_radius" value="0.035"/>
  <xacro:property name="wheel_width" value="0.021"/>
  <xacro:property name="wheel_separation" value="0.230"/>
  <xacro:property name="caster_radius" value="0.012"/>

  <xacro:macro name="kobuki">

    <!-- Base footprint (ground projection) -->
    <link name="base_footprint"/>

    <!-- Base link -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <mass value="2.4"/>
        <xacro:cylinder_inertia m="2.4" r="${base_radius}" h="${base_height}"/>
      </inertial>
    </link>

    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <!-- Left Wheel -->
    <link name="wheel_left_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="0.1"/>
        <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>

    <joint name="wheel_left_joint" type="continuous">
      <origin xyz="0.0 ${wheel_separation/2} 0.0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="wheel_left_link"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Right Wheel -->
    <link name="wheel_right_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <mass value="0.1"/>
        <xacro:cylinder_inertia m="0.1" r="${wheel_radius}" h="${wheel_width}"/>
      </inertial>
    </link>

    <joint name="wheel_right_joint" type="continuous">
      <origin xyz="0.0 ${-wheel_separation/2} 0.0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="wheel_right_link"/>
      <axis xyz="0 1 0"/>
    </joint>

    <!-- Front Caster -->
    <link name="caster_front_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <xacro:sphere_inertia m="0.05" r="${caster_radius}"/>
      </inertial>
    </link>

    <joint name="caster_front_joint" type="fixed">
      <origin xyz="0.115 0.0 ${caster_radius - wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="caster_front_link"/>
    </joint>

    <!-- Rear Caster -->
    <link name="caster_rear_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
        <material name="dark_grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${caster_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <xacro:sphere_inertia m="0.05" r="${caster_radius}"/>
      </inertial>
    </link>

    <joint name="caster_rear_joint" type="fixed">
      <origin xyz="-0.135 0.0 ${caster_radius - wheel_radius}" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="caster_rear_link"/>
    </joint>

    <!-- Gyro Frame -->
    <link name="gyro_link"/>

    <joint name="gyro_joint" type="fixed">
      <origin xyz="0.056 0.0 0.020" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="gyro_link"/>
    </joint>

    <!-- Cliff Sensors -->
    <link name="cliff_sensor_left_link"/>
    <joint name="cliff_sensor_left_joint" type="fixed">
      <origin xyz="0.08 0.13 0.01" rpy="0 ${pi/2} 0"/>
      <parent link="base_link"/>
      <child link="cliff_sensor_left_link"/>
    </joint>

    <link name="cliff_sensor_right_link"/>
    <joint name="cliff_sensor_right_joint" type="fixed">
      <origin xyz="0.08 -0.13 0.01" rpy="0 ${pi/2} 0"/>
      <parent link="base_link"/>
      <child link="cliff_sensor_right_link"/>
    </joint>

    <link name="cliff_sensor_front_link"/>
    <joint name="cliff_sensor_front_joint" type="fixed">
      <origin xyz="0.15 0.0 0.01" rpy="0 ${pi/2} 0"/>
      <parent link="base_link"/>
      <child link="cliff_sensor_front_link"/>
    </joint>

  </xacro:macro>

</robot>
